# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4667718c9412a45fdbe66beff64e3d5911f893199a6bd0d522fcdbdfaaa67b4d4f44c002610d1ab9f25af67d5f1915c5cce9b3881cdb36bc912084d738957d5

test:
  secret_key_base: bd0cea7fec264d62f308bb358140d536ad208f8840874166695166caf84ba3fdc6624455ca66849b4a7b71659ba5b055af8c1a80757db8ab03f806fdeada5f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
